---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: caddy
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201
  externalTrafficPolicy: Local
  selector:
    app: caddy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
