image:
  repository: vaultwarden/server
  tag: latest
  pullPolicy: IfNotPresent

domain: "https://vaultwarden.yukselcloud.com"

adminToken:
  value: "" # Set this to your admin token

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.0.204
  ports:
    http:
      port: 80

storage:
  data:
    name: "vaultwarden-data"
    size: "1Gi"
    class: "longhorn"
    path: "/data"
    keepPvc: true
    accessMode: "ReadWriteOnce"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
