namespace: media
replicaCount: 1

image:
  name: seerr
  repository: ghcr.io/seerr-team/seerr
  tag: develop

service:
  port: 5055
  loadBalancerIP: 192.168.0.218

resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Helsinki

volumeMounts:
  - name: config
    mountPath: /config

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: media-seerr-config
