apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: iperf3
      protocol: TCP
      name: iperf3
  selector:
    app: {{ .Release.Name }}
